// Code generated by "stringer -type=Opcode"; DO NOT EDIT.

package compiler

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CALL-0]
	_ = x[UNARY_MINUS-1]
	_ = x[BINARY_OP-2]
	_ = x[LOAD_NAME-3]
	_ = x[LOAD_CONST-4]
}

const _Opcode_name = "CALLUNARY_MINUSBINARY_OPLOAD_NAMELOAD_CONST"

var _Opcode_index = [...]uint8{0, 4, 15, 24, 33, 43}

func (i Opcode) String() string {
	if i < 0 || i >= Opcode(len(_Opcode_index)-1) {
		return "Opcode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Opcode_name[_Opcode_index[i]:_Opcode_index[i+1]]
}
