// Code generated by "stringer -type=LexemeType"; DO NOT EDIT.

package lexer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[STRING-0]
	_ = x[DIGIT_LITERAL-1]
	_ = x[STRING_LITERAL-2]
	_ = x[OPEN_BRACKET-3]
	_ = x[CLOSE_BRACKET-4]
	_ = x[PLUS-5]
	_ = x[MINUS-6]
	_ = x[MULT-7]
	_ = x[DIV-8]
	_ = x[NEW_LINE-9]
}

const _LexemeType_name = "STRINGDIGIT_LITERALSTRING_LITERALOPEN_BRACKETCLOSE_BRACKETPLUSMINUSMULTDIVNEW_LINE"

var _LexemeType_index = [...]uint8{0, 6, 19, 33, 45, 58, 62, 67, 71, 74, 82}

func (i LexemeType) String() string {
	if i < 0 || i >= LexemeType(len(_LexemeType_index)-1) {
		return "LexemeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LexemeType_name[_LexemeType_index[i]:_LexemeType_index[i+1]]
}
